### ISSUE TITLE
SPRINT 4 - Gabriel: Separação de amostras para prover a análise de QoE

### ISSUE THREAD

**Issue by GABRIELalmeida0** [GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede#11]

**Comment by F3L1CITY** [comment]
Os serviços que estamos utilizando começaram a rodar. Gabriel está monitorando o Prometheus, o Grafana e a API esta semana para que os serviços continuem em atividade enquanto monitoramos.
![WhatsApp Image 2023-12-18 at 20 25 06](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/95919755/2b6efb4f-48f8-48b2-aec9-13f92a769973)

**Comment by F3L1CITY** [comment]
No dia 18 de Dezembro ocorreu um erro ao subir o prometheus, pois um volume estava sem permissões administrativas
![WhatsApp Image 2023-12-18 at 21 02 33](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/95919755/6c6bcde2-4d29-4a12-9437-7ac58e37b94f)
Foi necessário 1h para debugar o código

**Comment by F3L1CITY** [comment]
Enfim, o código das métricas que precisavamos recolher e integração com o Crontab
![WhatsApp Image 2023-12-18 at 21 02 54](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/95919755/64c96d84-394e-4b6e-93cc-cd33ec2c8bcc)
