### ISSUE TITLE
SPRINT 4 - Julio: Criação dos Dockerfiles para empacotamento das aplicações do ambiente

### ISSUE THREAD

**Issue by GABRIELalmeida0** [GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede#13]

**Comment by jcfenuchi** [comment]
Como atividade inicial subi a imagem do container para o início do monitoramento das métricas.

**Comment by jcfenuchi** [comment]
Nesse sprint contribui com a imagem do container e com a configuração do streaming ao início de uma requisição de um usuário, que será usado para construção da simulação futuramente. Assim, para atuar como servidor foi escolhido o media MediaMTX por ser um servidor de mídia e proxy que permite publicar, ler e gravar vídeos e áudios. Além ser configurável por meio de um arquivo de configuração (mediamtx.yaml) e também por possuir suporte a protocolos de streaming como HLS, RTMP, RTSP, WebRTC. Para a publicação do streaming do vídeo no MediaMTX foi usado o FFmpeg que conhecido como uma ferramenta de linha de comando para criação, edição e conversão de vídeos, áudio e imagens. Além de ser muito leve e também pode ser usada para realizar a transmissão e recepção de vídeos com o ffplay.

Foi usado como protocolo principal o RTSP (Real Time Streaming Protocol) pelo uso do protocolo UDP na transmissão, que em caso da inferência de altos níveis de delay, jitter e packet loss na rede permite visualizar a degradação do vídeo, diferente do TCP que ocorre apenas o travamento devido à falta do buffer.


![lancamento](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/104705215/9561f7e1-6c69-4f1c-88f6-b2c15de97c00)

No mediamtx.yaml definimos o caminho da URL, protocolos, se vai ser leitura, gravação, proxy, oque fazer ao receber ou fechar uma requisição. No nosso caso usei um runOnDemand que significa uma ação que vai ocorrer quando um usuário solicitar o vídeo. É a ação é rodar o FFmpeg que vai realizar a publicação do vídeo para ser distribuído pelo servidor.

Bloco exemplo usado no mediamtx.yaml:
```yaml
  launch480p: 
     runOnDemand: ffmpeg -re -stream_loop -1 -i /videos/suttle_launch480p.mp4 -c copy -loglevel quiet -f rtsp rtsp://127.0.0.1:$RTSP_PORT/$MTX_PATH
     runOnDemandRestart: no
```
![mediamtx yml](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/104705215/461d4cfd-4363-4820-ab48-bff260533de1)

opções do FFmpeg
-c copy -> para usar o codec de vídeo e áudio na transmissão do vídeo.
-stream_loop -1 -> faz o vídeo ser transmitido em loop 
-loglevel quiet  -> Não exibir o output de log do FFmpeg 
-f rtsp -> formato usado para o streaming
 -i nome-arquivo -> diz qual vai ser o arquivo para ser realizado o streaming 
$RTSP_PORT/$MTX_PATH -> $RTSP_PORT porta padrão (8554)/ $MTX_PATH caminho do URL (/launch480p) 
-re -> ler o input de dados com o frame rate nativo

Para essa versão foi usado um vídeo randômico no formato mp4 em 3 resoluções 1080p, 720p e 480p publicados em URLs diferentes que podem ser acessados via comando.
```
ffplay -i rtsp://ip-do-container-servidor:8554/launch480p
ffplay -i rtsp://ip-do-container-servidor:8554/launch720p
ffplay -i rtsp://ip-do-container-servidor:8554/launch1080p
```
![streaming_docker](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/104705215/f59c371c-e208-4e4b-baa2-e470af58aade)

# DOCKER

![dockerfile](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/104705215/842c2596-6406-4cec-a416-24ee7e475b7f)


Foi utilizado o Docker para o empacotamento das ferramentas em um container, Assim para garantir a funcionalidade e facilitar no processo de entrega da aplicação servidora com apenas um comando 

MONTANDO A IMAGEM 
FROM -> nome da imagem referencia
RUN -> executa comando na hora do build do container.
WORKDIR -> determina qual é o diretorio home/preferencia do container
COPY -> copia os arquivos da maquina local para o container
CMD -> comando a ser executado ao inicio do container (pode ser sobresosto com ENTRYPOINT)

BUILDANDO A IMAGEM
```docker built -t mediamtx-local -f dockerfile.streamingserver .```
-t -> nome da imagem
-f -> nome do arquivo que deve ser usado para criar a imagem
. -> caminho onde está o arquivo
 
EXECUTANDO A IMAGEM

```docker run -it --rm NomedaImage```
-it -> usando para abrir o console do container
--rm -> apara o container após a sua parada

referencias: 
https://github.com/bluenviron/mediamtx
https://ffmpeg.org/ffmpeg.html#Stream-selection
https://trac.ffmpeg.org/wiki/StreamingGuide
https://docs.docker.com/engine/reference/builder/
https://docs.docker.com/engine/reference/run/
