### ISSUE TITLE
SPRINT 5 - Gabriel: Automatização do ambiente containerizado para simular o streaming

### ISSUE THREAD

**Issue by jcfenuchi** [GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede#15]
Automatização do ambiente containerizado para simular o streaming

**Comment by F3L1CITY** [comment]
Primeiramente foi feita a busca por códigos anteriores que já proporcionavam automatização, assim o novo código precisaria ser somente adaptado.

**Comment by F3L1CITY** [comment]
Após estudos, foi feito o código de automação do ambiente
![WhatsApp Image 2023-12-25 at 16 59 02](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/95919755/1cb065e4-845b-475f-a956-8f2aae5162fe)

**Comment by F3L1CITY** [comment]
Foi feito um código de automação em Python para fechar os processos que rodam o vídeo.

![WhatsApp Image 2023-12-25 at 19 48 27](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/95919755/f77c0c46-daa0-4dab-900a-d51dad92035d)

**Comment by F3L1CITY** [comment]
Após o código estar rodando, percebemos que não era preciso, pois o processo fechava sozinho, então retiramos o código feito anteriormente.

**Comment by F3L1CITY** [comment]
Afim de testes, foi setado no código Variáveis de Ambiente para ser possível assistir o vídeo stremado direto no contêiner do usuário do nosso cliente.

![WhatsApp Image 2023-12-25 at 19 50 25](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/95919755/68730b66-2b92-4a01-a551-fa940302595e)
