### ISSUE TITLE
SPRINT 5 - Ruth: Escolha e tratamento do vídeo para transmissão

### ISSUE THREAD

**Issue by jcfenuchi** [GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede#16]
Escolha e tratamento do vídeo para transmissão

**Comment by F3L1CITY** [comment]
Após analisar o crontab da semana anterior resolvemos criar um novo código.
![crontab](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/95919755/d81aba44-c70b-49ac-b450-472d73c3b2f5)

**Comment by F3L1CITY** [comment]
Foi feita a correção do crontab.
![crontabsemanapassada](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/95919755/96b3ccc9-880c-4059-81f4-2a48019caf2a)

**Comment by F3L1CITY** [comment]
Os testes no crontab foram bem sucedidos, então partimos para uma nova configuração e o código agora está programado para rodar 24h e mudar a cada 2 minutos.
![novocrontab](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/95919755/61c68591-f6a9-4c05-a3eb-bc23455b1119)
