### ISSUE TITLE
SPRINT 6 - Ruth: Exibição da perspectiva do vídeo ao usuário

### ISSUE THREAD

**Issue by GABRIELalmeida0** [GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede#17]

**Comment by F3L1CITY** [comment]
Hoje houve o teste de métricas para verificar o funcionamento. Foi possível analisar o vídeo pela perspectiva do usuário final do streaming, assim começamos a análise prática da Qualidade do Serviço.
![WhatsApp Image 2023-12-28 at 17 56 01](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/95919755/caf2c49a-07e6-4134-9d2a-a046a1be2bd8)

**Comment by F3L1CITY** [comment]
Hoje foi feita a transferência de modelo de relatório, onde começamos a escrever o relatório completo da entrega.
![Screenshot from 2024-01-03 03-39-18](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/95919755/18a0d981-7da4-4484-8ab5-a4ec4ee9bd31)

**Comment by F3L1CITY** [comment]
Também foi iniciado o modelo final de apresentação do Projeto.
![Screenshot from 2024-01-03 03-42-34](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/95919755/70a066df-19b7-4e4c-a76d-224ffb45615b)

**Comment by rcelest** [comment]
Durante toda a semana foi feita a análise dos vídeos baseados nas métricas capturadas na rede.
![commit final](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/95919755/38b39e4d-9c25-49b4-9b37-00d1493b9a20)
