### ISSUE TITLE
SPRINT 6 - Gabriel: Mapeamento do conjunto resultado do SSIM para a métrica comum MOS

### ISSUE THREAD

**Issue by GABRIELalmeida0** [GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede#18]

**Comment by F3L1CITY** [comment]
Tivemos uma reunião online no feriado para continuar dando andamento ao código da aplicação.
![WhatsApp Image 2024-01-01 at 17 54 39](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/95919755/3078c219-8150-4b49-8d11-81ddc7bb5a03)

**Comment by F3L1CITY** [comment]
Foi criado um código para automatizar a criação do Dataset.
![a4f80140-77f9-4b61-a5be-7c570e6bafd9](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/95919755/3e7e4e69-72dc-46f5-8318-48d96f4d5349)

**Comment by F3L1CITY** [comment]
Após finalização do código foi possível criar as subseções que faltavam na wiki do projeto. 

![6261eed3-c4a6-4495-92c9-617fe540d550](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/95919755/3f391332-cd45-408f-bbc6-213c47b8e622)

**Comment by F3L1CITY** [comment]
Fizemos um vídeo de amostragem da usabilidade atual da ferramenta:

![obs](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/95919755/ad4b66e4-6ea7-4927-b282-2c7ec6e953c6)


![obs2](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/95919755/25efd6d4-b3ec-4a3c-aa25-a5cc206f3111)
