### ISSUE TITLE
SPRINT 6 - Julio: Captura das métricas do SSIM com base no vídeo recebido e o original

### ISSUE THREAD

**Issue by GABRIELalmeida0** [GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede#19]

**Comment by jcfenuchi** [comment]
Houve uma mudança no código do app.py antigo para o novo, devido à degradação Não estar acontecendo no vídeo, agora o jitter delay e loss está sendo aplicado à interface s1-eth2 do switch que interliga o d1 e d2. Tornando a degradação no vídeo recebido coerente com o estado dos parâmetros da rede.

![commit-app-py](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/104705215/4d044e1a-efc2-4cb0-abd8-d95d9f6ad358)

Outra alteração foi a remoção do código de alteração da rede da imagem Docker.

**Comment by jcfenuchi** [comment]
#### Criação do curl.py 

```python
from requests import *
import numpy as np

list_of_number = []
for d in range(0, 201, 10):
    for j in range(0, 201, 10):
        for l in np.arange(0.0, 3.1, 0.5):
            network = {"node_name":"d2", "delay":f"{d}ms", "jitter":f"{j}ms", "loss":f"{l}%"}
            list_of_number.append(network)
list_of_number = np.array(list_of_number)

for request_params in list_of_number:
    print(f"Iniciando requisição: delay={request_params['delay']}, jitter={request_params['jitter']}, loss={request_params['loss']} .")
    experiment = get("http://localhost:5000/capture_streaming", params=request_params)
    print("Experimento Finalizado!.")
```
Esse código permite automatiza a solicitação das requisições a API para coleta das métricas de SSIM, que realizara requisições no período de 0-200ms de delay com saltos de 10ms, 0-200ms de jitter com saltos de 10ms e 0.0-3.0% de packet loss com um salto de 0.5%, ou seja, 10ms de delay será aplicado as seguintes requisições.
```
Iniciando requisição: delay=10ms, jitter=0ms, loss=0.0% .
Iniciando requisição: delay=10ms, jitter=0ms, loss=0.5% .
Iniciando requisição: delay=10ms, jitter=0ms, loss=1.0% .
Iniciando requisição: delay=10ms, jitter=0ms, loss=1.5% .
Iniciando requisição: delay=10ms, jitter=0ms, loss=2.0% .
Iniciando requisição: delay=10ms, jitter=0ms, loss=2.5% .
Iniciando requisição: delay=10ms, jitter=0ms, loss=3.0% .
Iniciando requisição: delay=10ms, jitter=10ms, loss=0.0% .
Iniciando requisição: delay=10ms, jitter=10ms, loss=0.5% .
...
...
...
Iniciando requisição: delay=10ms, jitter=200ms, loss=1.5% .
Iniciando requisição: delay=10ms, jitter=200ms, loss=2.0% .
Iniciando requisição: delay=10ms, jitter=200ms, loss=2.5% .
Iniciando requisição: delay=10ms, jitter=200ms, loss=3.0% .
```
Cada requisição gera a seguinte saída no containernet.py

```txt
alterando parametros da rede para 200ms 200ms 1.0% ...
Criando Experimento-3162 ...
iniciando a captura do video ...
iniciando a comparação dos videos ...
finalizado!
Excluindo video recebido e finalizando experimento.

```

Foi adicionado também a opção de Não salvar o vídeo recebido pelo usuário para simplificar e economizar armazenamento tendo em vista que deu mais de 3000 requisições.

```python
# para salvar o video recebido pelo usuario basta apenas colocar save_video=True!
app = App(net, default_url="rtsp://10.0.0.1:8554/launch480p15s", save_video=False)
app.start_app().run()
```

Que Após a execução de todo o previsto será criando a seguinte tabela:

![dataset-ssim](https://github.com/GABRIELalmeida0/Projeto-integrador-Servico-de-Monitoramento-de-KPI-de-Rede/assets/104705215/e64224fa-20df-4419-94ec-a9f73242b778)


Também foi gerado um tar.gz com os dados e o CSV final e o código de tratamento do CSV, que será disponibilizado no repositório *GitHub*.
```bash
dataset_ssim.tar.gz
```
